spin_manifest_version = 2

[application]
name = "aos-chal-two"
version = "0.1.0"
authors = ["Dimitri <5898931+dimitrilw@users.noreply.github.com>"]
description = "Fermyon advent-of-spin 2023, challenge 2"

[[trigger.http]]
route = "/..."
component = "aos-chal-two"

[component.aos-chal-two]
source = "main.wasm"
allowed_outbound_hosts = []
[component.aos-chal-two.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
watch = ["**/*.go", "go.mod"]
